name: Deploy SnapHire

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/SnapHire

            git pull origin main

            cd backend
            npm ci
            npm run build
            pm2 restart backend

            cd ../frontend
            npm ci
            NODE_OPTIONS="--max-old-space-size=2048" npm run build
            pm2 restart frontend

            sudo systemctl reload nginx